In [1]:
pip install jupyterlab

You should consider upgrading via the 'C:\Users\okuyy\AppData\Local\Programs\Python\Python38\python.exe -m pip install --upgrade pip' command.


In [ ]:
!pip install opendatasets
import opendatasets as od
od.download("https://www.kaggle.com/ananthu017/emotion-detection-fer")


In [ ]:
! pip install wheel
! pip install pandas
import pandas as pd
import os

! pip install scikit-image
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt

! pip install -U scikit-learn scipy matplotlib

In [ ]:
Categories = ['angry','disgusted','fearful', 'happy', 'neutral', 'sad', 'surprised']

flat_data_arr_test = [] #input array
target_arr_test = [] #output array
datadir_test = 'C:/Users/okuyy/Desktop/NUS/Y3S1/CS3244/Project/emotion-detection-fer/test' 
for i in Categories:
    print(f'loading... category : {i}')
    path = os.path.join(datadir_test, i)
    for img in os.listdir(path):
        img_array = imread(os.path.join(path, img))
        img_resized = resize(img_array, (48, 48))
        flat_data_arr_test.append(img_resized.flatten())
        target_arr_test.append(Categories.index(i))
    print(f'test loaded category:{i} successfully')

flat_data_arr_train = [] #input array
target_arr_train = [] #output array
datadir_train = 'C:/Users/okuyy/Desktop/NUS/Y3S1/CS3244/Project/emotion-detection-fer/train' 
for i in Categories:
    print(f'loading... category : {i}')
    path = os.path.join(datadir_train, i)
    for img in os.listdir(path):
        img_array = imread(os.path.join(path, img))
        img_resized = resize(img_array ,(48, 48))
        flat_data_arr_train.append(img_resized.flatten())
        target_arr_train.append(Categories.index(i))
    print(f'train loaded category:{i} successfully')

In [ ]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
flat_data_test = np.array(flat_data_arr_test)
target_test = np.array(target_arr_test)
df_test = pd.DataFrame(flat_data_test) #dataframe
df_test['Target'] = target_test
x_test =df_test.iloc[:,:-1] #input data 
y_test =df_test.iloc[:,-1] #output data

flat_data_train = np.array(flat_data_arr_train)
target_train = np.array(target_arr_train)
df_train = pd.DataFrame(flat_data_train) #dataframe
df_train['Target'] = target_train
x_train =df_train.iloc[:,:-1] #input data 
y_train =df_train.iloc[:,-1] #output data

In [8]:
svc_rbf_c01 = svm.SVC(C=0.1, kernel = 'rbf', gamma = 'auto', verbose = True)
svc_rbf_c01.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_rbf_c01.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained we+-96+ll with the given images
The predicted Data is :
[3 3 3 ... 3 3 3]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 25.090554471997773% accurate


In [13]:
svc_poly_c1_degree3 = svm.SVC(C=1, kernel = 'poly', degree = 3, gamma = 'auto', verbose = True)
svc_poly_c1_degree3.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_poly_c1_degree3.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained well with the given images
The predicted Data is :
[3 3 3 ... 3 3 3]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 27.626079687935356% accurate


In [7]:
svc_poly_c10_degree3 = svm.SVC(C=10, kernel = 'poly', degree = 3, gamma = 'auto', verbose = True)
svc_poly_c10_degree3.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_poly_c10_degree3.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained well with the given images
The predicted Data is :
[3 3 4 ... 3 3 3]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 35.483421565895796% accurate


In [ ]:
svc_poly_c40_degree3 = svm.SVC(C=40, kernel = 'poly', degree = 3, gamma = 'auto', verbose = True)
svc_poly_c40_degree3.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_poly_c40_degree3.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained well with the given images
The predicted Data is :
[3 5 4 ... 3 3 4]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 39.20312064641961% accurate


In [8]:
svc_poly_c100_degree5 = svm.SVC(C=100, kernel = 'poly', degree = 5, gamma = 'auto', verbose = True)
svc_poly_c100_degree5.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_poly_c100_degree5.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained well with the given images
The predicted Data is :
[3 3 4 ... 3 3 3]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 33.1568682084146% accurate


In [7]:
svc_poly_c1_degree5 = svm.SVC(C=1, kernel = 'poly', degree = 5, gamma = 'auto', verbose = True)
svc_poly_c1_degree5.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_poly_c1_degree5.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained well with the given images
The predicted Data is :
[3 3 3 ... 3 3 3]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 25.57815547506269% accurate


In [9]:
svc_poly_c500_degree5 = svm.SVC(C=500, kernel = 'poly', degree = 5, gamma = 'auto', verbose = True)
svc_poly_c500_degree5.fit(x_train,y_train)
print('The Model is trained well with the given images')

y_pred = svc_poly_c500_degree5.predict(x_test)
print("The predicted Data is :")
print(y_pred)

print("The actual data is:")
print(np.array(y_test)) 

print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

[LibSVM]The Model is trained well with the given images
The predicted Data is :
[2 5 4 ... 3 3 3]
The actual data is:
[0 0 0 ... 6 6 6]
The model is 37.698523265533574% accurate
